[theme]
base                = "light"
primaryColor        = "#6DB0E2"
backgroundColor     = "#F4F6F9"
secondaryBackgroundColor = "#FFFFFF"
textColor           = "#1A1A2E"
font                = "sans serif"

[client]
toolbarMode         = "minimal"

[server]
headless            = true
enableCORS          = false

[browser]
gatherUsageStats    = false
